// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FTFrame.BLL.Model
{
    /// <summary>
    /// 档案主表
    /// </summary>
    public partial class ar_archive
    {
        /// <summary>
        /// 主键
        /// </summary>
        public long id { get; set; }
        /// <summary>
        /// 人员Id
        /// </summary>
        public long? member_id { get; set; }
        /// <summary>
        /// 档号
        /// </summary>
        public string archive_number { get; set; }
        /// <summary>
        /// 题名
        /// </summary>
        public string archive_title { get; set; }
        /// <summary>
        /// 主题词
        /// </summary>
        public string archive_key { get; set; }
        /// <summary>
        /// 密级_字典code
        /// </summary>
        public string archive_security_code { get; set; }
        /// <summary>
        /// 所属年度
        /// </summary>
        public int? archive_year { get; set; }
        /// <summary>
        /// 关联部门id
        /// </summary>
        public long? department_id { get; set; }
        /// <summary>
        /// 目录号
        /// </summary>
        public string archive_catalog { get; set; }
        /// <summary>
        /// 案卷号
        /// </summary>
        public string archive_dossier { get; set; }
        /// <summary>
        /// 创建用户
        /// </summary>
        public string add_user { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public DateTime? add_time { get; set; }
        /// <summary>
        /// 修改用户
        /// </summary>
        public string mod_user { get; set; }
        /// <summary>
        /// 修改时间
        /// </summary>
        public DateTime? mod_time { get; set; }
        /// <summary>
        /// 删除状态 0有效 1删除
        /// </summary>
        public short? is_del { get; set; }
    }
}