// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FTFrame.BLL.Model
{
    /// <summary>
    /// 人员工作经历
    /// </summary>
    public partial class bs_member_experience
    {
        /// <summary>
        /// 主键
        /// </summary>
        public long id { get; set; }
        /// <summary>
        /// 关联的人员id
        /// </summary>
        public long member_id { get; set; }
        /// <summary>
        /// 职务名称
        /// </summary>
        public string post_name { get; set; }
        /// <summary>
        /// 部门
        /// </summary>
        public string department { get; set; }
        /// <summary>
        /// 工作单位
        /// </summary>
        public string organization { get; set; }
        /// <summary>
        /// 入职日期
        /// </summary>
        public DateTime? join_date { get; set; }
        /// <summary>
        /// 创建用户
        /// </summary>
        public string add_user { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public DateTime? add_time { get; set; }
        /// <summary>
        /// 修改用户
        /// </summary>
        public string mod_user { get; set; }
        /// <summary>
        /// 修改时间
        /// </summary>
        public DateTime? mod_time { get; set; }
        /// <summary>
        /// 删除状态 0有效 1删除
        /// </summary>
        public short? is_del { get; set; }
    }
}