// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FTFrame.BLL.Model
{
    /// <summary>
    /// 人员基本信息
    /// </summary>
    public partial class bs_member
    {
        /// <summary>
        /// 主键
        /// </summary>
        public long id { get; set; }
        /// <summary>
        /// 关联的用户id
        /// </summary>
        public long user_id { get; set; }
        /// <summary>
        /// 姓名
        /// </summary>
        public string name { get; set; }
        /// <summary>
        /// 电话
        /// </summary>
        public string phone { get; set; }
        /// <summary>
        /// 头像图片
        /// </summary>
        public string image_head { get; set; }
        /// <summary>
        /// 在岗状态_字典code
        /// </summary>
        public string onguard_code { get; set; }
        /// <summary>
        /// 政治面貌_字典code
        /// </summary>
        public string polity_code { get; set; }
        /// <summary>
        /// 岗位_字典code
        /// </summary>
        public string job_code { get; set; }
        /// <summary>
        /// 入职日期
        /// </summary>
        public DateTime? join_date { get; set; }
        /// <summary>
        /// 创建用户
        /// </summary>
        public string add_user { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public DateTime? add_time { get; set; }
        /// <summary>
        /// 修改用户
        /// </summary>
        public string mod_user { get; set; }
        /// <summary>
        /// 修改时间
        /// </summary>
        public DateTime? mod_time { get; set; }
        /// <summary>
        /// 删除状态 0有效 1删除
        /// </summary>
        public short? is_del { get; set; }
    }
}