// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FTFrame.BLL.Model
{
    /// <summary>
    /// 计算_全院指标分数
    /// </summary>
    public partial class ca_index_corp
    {
        /// <summary>
        /// 主键
        /// </summary>
        public long id { get; set; }
        /// <summary>
        /// 一级指标的code（字典）
        /// </summary>
        public string index_code { get; set; }
        /// <summary>
        /// 法院id
        /// </summary>
        public long? corp_id { get; set; }
        /// <summary>
        /// 时期（月度、季度的字符串）
        /// </summary>
        public string period { get; set; }
        /// <summary>
        /// 分数
        /// </summary>
        public decimal? point { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public DateTime? add_time { get; set; }
    }
}