// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FTFrame.BLL.Model
{
    /// <summary>
    /// 计算_部门分数
    /// </summary>
    public partial class ca_score_department
    {
        /// <summary>
        /// 主键
        /// </summary>
        public long id { get; set; }
        /// <summary>
        /// 部门Id
        /// </summary>
        public long? department_id { get; set; }
        /// <summary>
        /// 时期（月度、季度的字符串）
        /// </summary>
        public string period { get; set; }
        /// <summary>
        /// 分数
        /// </summary>
        public decimal? point { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public DateTime? add_time { get; set; }
    }
}