// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FTFrame.BLL.Model
{
    /// <summary>
    /// 党组决议事项明细
    /// </summary>
    public partial class ev_party_resolution_department
    {
        /// <summary>
        /// 主键
        /// </summary>
        public long id { get; set; }
        /// <summary>
        /// 关联党组决议事项id
        /// </summary>
        public long? party_resolution_id { get; set; }
        /// <summary>
        /// 关联部门id
        /// </summary>
        public long? department_id { get; set; }
        /// <summary>
        /// 责任人员
        /// </summary>
        public long? response_member_id { get; set; }
        /// <summary>
        /// 责任类型:1主办,2协办
        /// </summary>
        public short? response_member_type { get; set; }
        /// <summary>
        /// 督办人员
        /// </summary>
        public long? supervisor_member_id { get; set; }
        /// <summary>
        /// 督办状态_字典code
        /// </summary>
        public string supervisor_code { get; set; }
        /// <summary>
        /// 接受日期
        /// </summary>
        public DateTime? accept_date { get; set; }
        /// <summary>
        /// 完成日期
        /// </summary>
        public DateTime? finish_date { get; set; }
        /// <summary>
        /// 执行进度
        /// </summary>
        public decimal? progress { get; set; }
        /// <summary>
        /// 最新进展
        /// </summary>
        public string last_headway { get; set; }
        /// <summary>
        /// 创建用户
        /// </summary>
        public string add_user { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public DateTime? add_time { get; set; }
        /// <summary>
        /// 修改用户
        /// </summary>
        public string mod_user { get; set; }
        /// <summary>
        /// 修改时间
        /// </summary>
        public DateTime? mod_time { get; set; }
        /// <summary>
        /// 删除状态 0有效 1删除
        /// </summary>
        public short? is_del { get; set; }
    }
}