// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FTFrame.BLL.Model
{
    /// <summary>
    /// 预警事项
    /// </summary>
    public partial class ev_warning
    {
        /// <summary>
        /// 主键
        /// </summary>
        public long id { get; set; }
        /// <summary>
        /// 预警类型_字典code
        /// </summary>
        public string warning_code { get; set; }
        /// <summary>
        /// 预警事项名称
        /// </summary>
        public string warning_name { get; set; }
        /// <summary>
        /// 预警事项说明
        /// </summary>
        public string warning_desc { get; set; }
        /// <summary>
        /// 关联人员id
        /// </summary>
        public long? member_id { get; set; }
        /// <summary>
        /// 关联部门id
        /// </summary>
        public long? department_id { get; set; }
        /// <summary>
        /// 响应结果_字典code
        /// </summary>
        public string response_code { get; set; }
        /// <summary>
        /// 响应时间
        /// </summary>
        public DateTime? response_time { get; set; }
        /// <summary>
        /// 响应措施
        /// </summary>
        public string response_measure { get; set; }
        /// <summary>
        /// 创建用户
        /// </summary>
        public string add_user { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public DateTime? add_time { get; set; }
        /// <summary>
        /// 修改用户
        /// </summary>
        public string mod_user { get; set; }
        /// <summary>
        /// 修改时间
        /// </summary>
        public DateTime? mod_time { get; set; }
        /// <summary>
        /// 删除状态 0有效 1删除
        /// </summary>
        public short? is_del { get; set; }
    }
}