// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FTFrame.BLL.Model
{
    /// <summary>
    /// 体检主表
    /// </summary>
    public partial class ex_examine
    {
        /// <summary>
        /// 主键
        /// </summary>
        public long id { get; set; }
        /// <summary>
        /// 指标模板Id
        /// </summary>
        public long? index_id { get; set; }
        /// <summary>
        /// 体检方式_字典code
        /// </summary>
        public string examine_code { get; set; }
        /// <summary>
        /// 评价方式_字典code
        /// </summary>
        public string evaluate_code { get; set; }
        /// <summary>
        /// 时期（月度、季度的字符串）
        /// </summary>
        public string period { get; set; }
        /// <summary>
        /// 创建用户
        /// </summary>
        public string add_user { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public DateTime? add_time { get; set; }
        /// <summary>
        /// 修改用户
        /// </summary>
        public string mod_user { get; set; }
        /// <summary>
        /// 修改时间
        /// </summary>
        public DateTime? mod_time { get; set; }
        /// <summary>
        /// 删除状态 0有效 1删除
        /// </summary>
        public short? is_del { get; set; }
    }
}