// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FTFrame.BLL.Model
{
    /// <summary>
    /// 人员体检主表
    /// </summary>
    public partial class ex_member
    {
        /// <summary>
        /// 主键
        /// </summary>
        public long id { get; set; }
        /// <summary>
        /// 关联的人员id
        /// </summary>
        public long? member_id { get; set; }
        /// <summary>
        /// 体检主表Id
        /// </summary>
        public long? examine_id { get; set; }
        /// <summary>
        /// 评价人
        /// </summary>
        public long? examine_user { get; set; }
        /// <summary>
        /// 是否已经评价过 0未评价过 1已评价
        /// </summary>
        public short? is_examined { get; set; }
        /// <summary>
        /// 创建用户
        /// </summary>
        public string add_user { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public DateTime? add_time { get; set; }
        /// <summary>
        /// 修改用户
        /// </summary>
        public string mod_user { get; set; }
        /// <summary>
        /// 修改时间
        /// </summary>
        public DateTime? mod_time { get; set; }
        /// <summary>
        /// 删除状态 0有效 1删除
        /// </summary>
        public short? is_del { get; set; }
    }
}