// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FTFrame.BLL.Model
{
    /// <summary>
    /// 人员体检指标明细
    /// </summary>
    public partial class ex_member_index
    {
        /// <summary>
        /// 主键
        /// </summary>
        public long id { get; set; }
        /// <summary>
        /// 人员体检主表id
        /// </summary>
        public long? examine_member_id { get; set; }
        /// <summary>
        /// 关联的三级指标id
        /// </summary>
        public long? index_level_3_id { get; set; }
        /// <summary>
        /// 评价人
        /// </summary>
        public long? examine_user { get; set; }
        /// <summary>
        /// 评价内容
        /// </summary>
        public string examine_content { get; set; }
        /// <summary>
        /// 评价分数
        /// </summary>
        public short? point { get; set; }
        /// <summary>
        /// 创建用户
        /// </summary>
        public string add_user { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public DateTime? add_time { get; set; }
        /// <summary>
        /// 修改用户
        /// </summary>
        public string mod_user { get; set; }
        /// <summary>
        /// 修改时间
        /// </summary>
        public DateTime? mod_time { get; set; }
        /// <summary>
        /// 删除状态 0有效 1删除
        /// </summary>
        public short? is_del { get; set; }
    }
}