// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FTFrame.BLL.Model
{
    /// <summary>
    /// 字典类型表
    /// </summary>
    public partial class sys_dict_type
    {
        /// <summary>
        /// 字典主键
        /// </summary>
        public long dict_id { get; set; }
        /// <summary>
        /// 字典名称
        /// </summary>
        public string dict_name { get; set; }
        /// <summary>
        /// 字典类型
        /// </summary>
        public string dict_type { get; set; }
        /// <summary>
        /// 状态（0正常 1停用）
        /// </summary>
        public string status { get; set; }
        /// <summary>
        /// 创建者
        /// </summary>
        public string create_by { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public DateTime? create_time { get; set; }
        /// <summary>
        /// 更新者
        /// </summary>
        public string update_by { get; set; }
        /// <summary>
        /// 更新时间
        /// </summary>
        public DateTime? update_time { get; set; }
        /// <summary>
        /// 备注
        /// </summary>
        public string remark { get; set; }
    }
}