// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FTFrame.BLL.Model
{
    /// <summary>
    /// 部门表
    /// </summary>
    public partial class sys_dept
    {
        /// <summary>
        /// 部门id
        /// </summary>
        public long dept_id { get; set; }
        /// <summary>
        /// 父部门id
        /// </summary>
        public long? parent_id { get; set; }
        /// <summary>
        /// 祖级列表
        /// </summary>
        public string ancestors { get; set; }
        /// <summary>
        /// 部门名称
        /// </summary>
        public string dept_name { get; set; }
        /// <summary>
        /// 显示顺序
        /// </summary>
        public int? order_num { get; set; }
        /// <summary>
        /// 负责人
        /// </summary>
        public string leader { get; set; }
        /// <summary>
        /// 联系电话
        /// </summary>
        public string phone { get; set; }
        /// <summary>
        /// 邮箱
        /// </summary>
        public string email { get; set; }
        /// <summary>
        /// 部门状态（0正常 1停用）
        /// </summary>
        public string status { get; set; }
        /// <summary>
        /// 删除标志（0代表存在 2代表删除）
        /// </summary>
        public string del_flag { get; set; }
        /// <summary>
        /// 创建者
        /// </summary>
        public string create_by { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public DateTime? create_time { get; set; }
        /// <summary>
        /// 更新者
        /// </summary>
        public string update_by { get; set; }
        /// <summary>
        /// 更新时间
        /// </summary>
        public DateTime? update_time { get; set; }
        /// <summary>
        /// 图标
        /// </summary>
        public string icon { get; set; }
        /// <summary>
        /// 资源类型,region,dept
        /// </summary>
        public string resource_tag { get; set; }
    }
}