// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FTFrame.BLL.Model
{
    /// <summary>
    /// 用户信息表
    /// </summary>
    public partial class sys_user
    {
        /// <summary>
        /// 用户ID
        /// </summary>
        public long user_id { get; set; }
        /// <summary>
        /// 部门ID
        /// </summary>
        public long? dept_id { get; set; }
        /// <summary>
        /// 用户账号
        /// </summary>
        public string user_name { get; set; }
        /// <summary>
        /// 用户昵称
        /// </summary>
        public string nick_name { get; set; }
        /// <summary>
        /// 用户类型（00系统用户）
        /// </summary>
        public string user_type { get; set; }
        /// <summary>
        /// 用户邮箱
        /// </summary>
        public string email { get; set; }
        /// <summary>
        /// 手机号码
        /// </summary>
        public string phonenumber { get; set; }
        /// <summary>
        /// 用户性别（0男 1女 2未知）
        /// </summary>
        public string sex { get; set; }
        /// <summary>
        /// 头像地址
        /// </summary>
        public string avatar { get; set; }
        /// <summary>
        /// 密码
        /// </summary>
        public string password { get; set; }
        /// <summary>
        /// 帐号状态（0正常 1停用）
        /// </summary>
        public string status { get; set; }
        /// <summary>
        /// 删除标志（0代表存在 2代表删除）
        /// </summary>
        public string del_flag { get; set; }
        /// <summary>
        /// 最后登录IP
        /// </summary>
        public string login_ip { get; set; }
        /// <summary>
        /// 最后登录时间
        /// </summary>
        public DateTime? login_date { get; set; }
        /// <summary>
        /// 创建者
        /// </summary>
        public string create_by { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public DateTime? create_time { get; set; }
        /// <summary>
        /// 更新者
        /// </summary>
        public string update_by { get; set; }
        /// <summary>
        /// 更新时间
        /// </summary>
        public DateTime? update_time { get; set; }
        /// <summary>
        /// 备注
        /// </summary>
        public string remark { get; set; }
    }
}