// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FTFrame.BLL.Model
{
    /// <summary>
    /// 字典数据表
    /// </summary>
    public partial class sys_dict_data
    {
        /// <summary>
        /// 字典编码
        /// </summary>
        public long dict_code { get; set; }
        /// <summary>
        /// 字典排序
        /// </summary>
        public int? dict_sort { get; set; }
        /// <summary>
        /// 字典标签
        /// </summary>
        public string dict_label { get; set; }
        /// <summary>
        /// 字典键值
        /// </summary>
        public string dict_value { get; set; }
        /// <summary>
        /// 字典类型
        /// </summary>
        public string dict_type { get; set; }
        /// <summary>
        /// 样式属性（其他样式扩展）
        /// </summary>
        public string css_class { get; set; }
        /// <summary>
        /// 表格回显样式
        /// </summary>
        public string list_class { get; set; }
        /// <summary>
        /// 是否默认（Y是 N否）
        /// </summary>
        public string is_default { get; set; }
        /// <summary>
        /// 状态（0正常 1停用）
        /// </summary>
        public string status { get; set; }
        /// <summary>
        /// 创建者
        /// </summary>
        public string create_by { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public DateTime? create_time { get; set; }
        /// <summary>
        /// 更新者
        /// </summary>
        public string update_by { get; set; }
        /// <summary>
        /// 更新时间
        /// </summary>
        public DateTime? update_time { get; set; }
        /// <summary>
        /// 备注
        /// </summary>
        public string remark { get; set; }
    }
}