// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace FTFrame.Model
{
    [Table("ft_ctrl_list_files_bind")]
    public partial class FtCtrlListFilesBind
    {
        [Key]
        [Column("fileid")]
        [StringLength(36)]
        public string Fileid { get; set; }
        [Key]
        [Column("userid")]
        [StringLength(36)]
        public string Userid { get; set; }
    }
}