// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace FTFrame.Model
{
    [Table("ft_ctrl_list_files")] 
    public partial class FtCtrlListFiles
    {
        [Key]
        [Column("partid")]
        [StringLength(36)]
        public string Partid { get; set; }
        [Key]
        [Column("fileid")]
        [StringLength(36)]
        public string Fileid { get; set; }
        [Column("filepath")]
        [StringLength(64)]
        public string Filepath { get; set; }
        [Column("filecap")]
        [StringLength(48)]
        public string Filecap { get; set; }
        [Column("userid")]
        [StringLength(36)]
        public string Userid { get; set; }
        [Column("addtime", TypeName = "datetime")]
        public DateTime? Addtime { get; set; }
        [Column("rows")]
        public int? Rows { get; set; }
        [Column("minutes")]
        public int? Minutes { get; set; }
    }
}