// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace FTFrame.Model
{
    /// <summary>
    /// 流程历史记录
    /// </summary>
    [Table("ft_flow_his")]
    public partial class FtFlowHis
    {
        /// <summary>
        /// 原始审批对象ID
        /// </summary>
        [Key]
        [Column("WorkID")]
        [StringLength(36)]
        public string WorkId { get; set; }
        /// <summary>
        /// 流程ID
        /// </summary>
        [Key]
        [Column("FlowID")]
        [StringLength(36)]
        public string FlowId { get; set; }
        /// <summary>
        /// 状态值
        /// </summary>
        [Key]
        public int StepValue { get; set; }
        /// <summary>
        /// 位置值
        /// </summary>
        [Key]
        [Column("StepID")]
        public int StepId { get; set; }
        /// <summary>
        /// 变更时间
        /// </summary>
        [Key]
        [Column(TypeName = "datetime")]
        public DateTime AlterTime { get; set; }
        /// <summary>
        /// 操作用户ID
        /// </summary>
        [Column("UserID")]
        [StringLength(36)]
        public string UserId { get; set; }
        /// <summary>
        /// 审批结果
        /// </summary>
        [StringLength(50)]
        public string Result { get; set; }
        /// <summary>
        /// 审批备注说明
        /// </summary>
        [StringLength(255)]
        public string Mimo { get; set; }
        /// <summary>
        /// 位置值显示
        /// </summary>
        [StringLength(128)]
        public string StepCaption { get; set; }
        /// <summary>
        /// 是否为终结节点
        /// </summary>
        public short IsEnd { get; set; }
        /// <summary>
        /// 是否为起始节点
        /// </summary>
        public short IsStart { get; set; }
        /// <summary>
        /// 是否已结束（取消，拒绝等）
        /// </summary>
        public short IsFinished { get; set; }
    }
}