// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace FTFrame.Model
{
    /// <summary>
    /// 下一步流程审批人
    /// </summary>
    [Table("ft_flow_next_user")]
    public partial class FtFlowNextUser
    {
        /// <summary>
        /// 原始审批对象ID
        /// </summary>
        [Key]
        [Column("WorkID")]
        [StringLength(36)]
        public string WorkId { get; set; }
        /// <summary>
        /// 流程ID
        /// </summary>
        [Key]
        [Column("FlowID")]
        [StringLength(36)]
        public string FlowId { get; set; }
        [Key]
        [Column("UserID")]
        [StringLength(36)]
        public string UserId { get; set; }
    }
}