// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace FTFrame.Model
{
    /// <summary>
    /// 流程列表
    /// </summary>
    [Table("ft_flow_list")]
    public partial class FtFlowList
    {
        /// <summary>
        /// 流程ID
        /// </summary>
        [Key]
        [Column("FlowID")]
        [StringLength(36)]
        public string FlowId { get; set; }
        /// <summary>
        /// 流程名称
        /// </summary>
        [StringLength(64)]
        public string FlowName { get; set; }
        /// <summary>
        /// 类型字典ID
        /// </summary>
        [StringLength(50)]
        public string DicCode { get; set; }
        /// <summary>
        /// 备注说明
        /// </summary>
        [StringLength(255)]
        public string Mimo { get; set; }
        /// <summary>
        /// 排序值
        /// </summary>
        public int? OrderRank { get; set; }
        /// <summary>
        /// 主表表名
        /// </summary>
        [StringLength(255)]
        public string MainTable { get; set; }
        /// <summary>
        /// 流程定义XML
        /// </summary>
        [Column(TypeName = "text")]
        public string FlowDefine { get; set; }
        /// <summary>
        /// 结束时的操作，换行添加多个
        /// </summary>
        [Column(TypeName = "text")]
        public string EndOperation { get; set; }
        /// <summary>
        /// 被拒绝状态值
        /// </summary>
        public int? RejectStatValue { get; set; }
        /// <summary>
        /// 状态值写入列（若需要）
        /// </summary>
        [StringLength(255)]
        public string StatColumn { get; set; }
        /// <summary>
        /// 状态值显示写入列（若需要）
        /// </summary>
        [StringLength(255)]
        public string StatCaptionColumn { get; set; }
        /// <summary>
        /// 状态值及其显示的枚举
        /// </summary>
        [Column(TypeName = "text")]
        public string StatCaptionEnum { get; set; }
        [Column("pid")]
        [StringLength(36)]
        public string Pid { get; set; }
        [Column("fmem")]
        [StringLength(36)]
        public string Fmem { get; set; }
        [Column("modfmem")]
        [StringLength(36)]
        public string Modfmem { get; set; }
        [Column("addtime", TypeName = "datetime")]
        public DateTime? Addtime { get; set; }
        [Column("updatetime", TypeName = "datetime")]
        public DateTime? Updatetime { get; set; }
        [Column("dydata")]
        [StringLength(255)]
        public string Dydata { get; set; }
        [Column("stat")]
        public short? Stat { get; set; }
        [Column("flow")]
        public int? Flow { get; set; }
        [Column("flowpos")]
        public int? Flowpos { get; set; }
    }
}