// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace FTFrame.Model
{
    /// <summary>
    /// 下一步流程信息
    /// </summary>
    [Table("ft_flow_next")]
    public partial class FtFlowNext
    {
        /// <summary>
        /// 原始审批对象ID
        /// </summary>
        [Key]
        [Column("WorkID")]
        [StringLength(36)]
        public string WorkId { get; set; }
        /// <summary>
        /// 流程ID
        /// </summary>
        [Key]
        [Column("FlowID")]
        [StringLength(36)]
        public string FlowId { get; set; }
        /// <summary>
        /// 状态值
        /// </summary>
        public int? StepValue { get; set; }
        /// <summary>
        /// 位置值
        /// </summary>
        [Column("StepID")]
        public int? StepId { get; set; }
        /// <summary>
        /// 添加时间
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime? AddTime { get; set; }
        /// <summary>
        /// 位置值显示
        /// </summary>
        [StringLength(128)]
        public string StepCaption { get; set; }
    }
}