// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace FTFrame.Model
{
    [Table("ft_ftdp_formflog")]
    public partial class FtFtdpFormflog
    {
        [Key]
        [Column("fid")]
        [StringLength(36)]
        public string Fid { get; set; }
        [Key]
        [Column("ftype")]
        public int Ftype { get; set; }
        [Column("fmem")]
        [StringLength(255)]
        public string Fmem { get; set; }
        [Required]
        [Column("binddata")]
        [StringLength(255)]
        public string Binddata { get; set; }
        [Key]
        [Column("addtime", TypeName = "datetime")]
        public DateTime Addtime { get; set; }
        [Key]
        [Column("fvalue")]
        public int Fvalue { get; set; }
        [Key]
        [Column("fpos")]
        public int Fpos { get; set; }
    }
}