// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace FTFrame.Model
{
    [Table("ft_ftdp_apiset")]
    public partial class FtFtdpApiset
    {
        [Key]
        [StringLength(250)]
        public string ApiPath { get; set; }
        [Column("PartID")]
        [StringLength(50)]
        public string PartId { get; set; }
        [Column("PageID")]
        [StringLength(50)]
        public string PageId { get; set; }
        [StringLength(10)]
        public string ApiType { get; set; }
        [Column("Set_List_Order")]
        [StringLength(150)]
        public string SetListOrder { get; set; }
        [Column("Set_List_Sql")]
        [StringLength(2000)]
        public string SetListSql { get; set; }
        [Column("Set_List_RowAll", TypeName = "text")]
        public string SetListRowAll { get; set; }
        [Column("Set_DyValue_DefineStr", TypeName = "text")]
        public string SetDyValueDefineStr { get; set; }
        [Column("Set_DyValue_ApiDefine", TypeName = "text")]
        public string SetDyValueApiDefine { get; set; }
        [Column("Set_DyValue_DefaultFID")]
        [StringLength(50)]
        public string SetDyValueDefaultFid { get; set; }
        [Column("Set_DyValue_FidCol")]
        [StringLength(50)]
        public string SetDyValueFidCol { get; set; }
        [Column("Set_DyValue_OpDefaultCol")]
        public short? SetDyValueOpDefaultCol { get; set; }
    }
}