// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace FTFrame.Model
{
    [Table("ft_ftdp_apidoc")]
    public partial class FtFtdpApidoc
    {
        [Key]
        [Column("FId")]
        [StringLength(36)]
        public string Fid { get; set; }
        [Key]
        [StringLength(250)]
        public string ApiPath { get; set; }
        [Column("PageID")]
        [StringLength(50)]
        public string PageId { get; set; }
        [StringLength(50)]
        public string PageCaption { get; set; }
        [StringLength(90)]
        public string DevUser { get; set; }
        [StringLength(10)]
        public string ApiType { get; set; }
        [StringLength(250)]
        public string Mimo { get; set; }
        [Column(TypeName = "text")]
        public string InputDesc { get; set; }
        [Column(TypeName = "text")]
        public string OutputDesc { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModTime { get; set; }
        [Column(TypeName = "text")]
        public string PostManJson { get; set; }
    }
}