// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace FTFrame.Model
{
    [Table("ft_ftdp_codeset")]
    [Index(nameof(Codekey), Name = "IX_ft_ftdp_codeset")]
    public partial class FtFtdpCodeset
    {
        [Key]
        [Column("fid")]
        [StringLength(36)]
        public string Fid { get; set; }
        [Column("devuser")]
        [StringLength(50)]
        public string Devuser { get; set; }
        [Column("dllname")]
        [StringLength(150)]
        public string Dllname { get; set; }
        [Column("codekey")]
        [StringLength(150)]
        public string Codekey { get; set; }
        [Column("codeval")]
        [StringLength(255)]
        public string Codeval { get; set; }
        [Column("returntype")]
        [StringLength(50)]
        public string Returntype { get; set; }
        [Column("modtime", TypeName = "datetime")]
        public DateTime? Modtime { get; set; }
        [Column("mimo")]
        [StringLength(255)]
        public string Mimo { get; set; }
    }
}