// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace FTFrame.Model
{
    [Table("ft_sites")]
    public partial class FtSites
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("siteid")]
        [StringLength(255)]
        public string Siteid { get; set; }
        [Column("sitehost")]
        [StringLength(255)]
        public string Sitehost { get; set; }
        [Column("siteport")]
        [StringLength(10)]
        public string Siteport { get; set; }
        [Column("sitepath")]
        [StringLength(255)]
        public string Sitepath { get; set; }
        [Column("sitecaption")]
        [StringLength(255)]
        public string Sitecaption { get; set; }
        [Column("sitegroup")]
        [StringLength(255)]
        public string Sitegroup { get; set; }
        [Column("sysuser")]
        [StringLength(255)]
        public string Sysuser { get; set; }
        [Column("syspasswd")]
        [StringLength(255)]
        public string Syspasswd { get; set; }
        [Column("siteversion")]
        public int Siteversion { get; set; }
        [Column("timeout")]
        public int? Timeout { get; set; }
        [Column("language")]
        [StringLength(10)]
        public string Language { get; set; }
        [Column("locked")]
        public short? Locked { get; set; }
    }
}